name: lector_ia
description: "E-reader con TTS Neural y reproducción en segundo plano."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  get_it: ^8.0.2

  # Navigation
  go_router: ^14.2.7

  # Book parsing
  epub_view: ^3.2.0
  pdfrx: 1.0.101

  # Audio
  audio_service: ^0.18.15
  just_audio: ^0.9.40
  audio_session: ^0.1.21

  # HTTP & networking
  dio: ^5.7.0
  connectivity_plus: ^6.0.3

  # Hashing for cache keys
  crypto: ^3.0.3

  # Local storage
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  shared_preferences: ^2.3.0

  # File access & permissions
  permission_handler: ^11.3.1
  file_picker: ^8.1.2

  # Reactive extensions (debounce en ReaderBloc)
  rxdart: ^0.27.7


  # UI
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  lottie: ^3.1.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/animations/


